{{- if or .Values.pocketbase.encryptionKey .Values.pocketbase.adminEmail -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-use-case-navigator.fullname" . }}
  labels:
    {{- include "ai-use-case-navigator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.pocketbase.encryptionKey }}
  encryption-key: {{ .Values.pocketbase.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.pocketbase.adminEmail }}
  admin-email: {{ .Values.pocketbase.adminEmail | b64enc | quote }}
  {{- end }}
  {{- if .Values.pocketbase.adminPassword }}
  admin-password: {{ .Values.pocketbase.adminPassword | b64enc | quote }}
  {{- end }}
{{- end }}
